### ISSUE TITLE
To-do: Ryder

### ISSUE THREAD

**Issue by EvilJackCarver** [Chatter42/AEIOUStation13#80]
- [ ]  Reduce bonus damage slightly
- [ ]  Mangled BBs need to be able to be recycled in an autolathe. Subtype of ammo, maybe?
- [ ]  Actually fix fake compass and sundial in the stock of LE edition
  * Possible runtime: Make it to where you have to be holding it to read the compass properly? Clock I don't care about, but the rifle will point east regardless of its `dir` if it's not being held, due to the way spriting works.
